name: tei-local
services:
  postgres:
    container_name: tei-postgres
    image: postgis/postgis:17-master
    command: postgres -c 'max_connections=500'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init://docker-entrypoint-initdb.d
volumes:
  postgres:
    name: tei-postgres.local
