name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '.github/graphics/**'
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      pr_no:
        description: "PR-numbered container set to deploy"
        type: number
        required: true

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr-selector.outputs.pr }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main if not specified as input
      - name: PR Number
        id: pr
        if: github.event.inputs.pr_no == null
        uses: bcgov-nr/action-get-pr@v0.0.1
      # Get the appropriate PR number output value depending on whether input was specified
      - name: PR Number Selector
        id: pr-selector
        run: |
          if [[ "${{ github.event.inputs.pr_no }}" == "" ]]; then
              echo "pr=${{ steps.pr.outputs.pr }}" >> $GITHUB_OUTPUT
          else
              echo "pr=${{ github.event.inputs.pr_no }}" >> $GITHUB_OUTPUT
          fi

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploy-test:
    name: Deploy (test)
    needs: [vars]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      environment: test
      db_user: app
      tag: ${{ needs.vars.outputs.pr }}

  # deploy-prod:
  #   name: Deploy (prod)
  #   needs: [deploy-test, vars]
  #   uses: ./.github/workflows/.deployer.yml
  #   secrets:
  #     oc_namespace: ${{ secrets.OC_NAMESPACE }}
  #     oc_token: ${{ secrets.OC_TOKEN }}
  #   with:
  #     environment: prod
  #     db_user: app
  #     tag: ${{ needs.vars.outputs.pr }}
  #     params:
  #       --set backend.deploymentStrategy=RollingUpdate
  #       --set global.autoscaling=true
  #       --set backend.pdb.enabled=true

  # promote:
  #   name: Promote Images
  #   needs: [deploy-prod, vars]
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     packages: write
  #   strategy:
  #     matrix:
  #       package: [migrations, backend]
  #   timeout-minutes: 1
  #   steps:
  #     - uses: shrink/actions-docker-registry-tag@v4
  #       with:
  #         registry: ghcr.io
  #         repository: ${{ github.repository }}/${{ matrix.package }}
  #         target: ${{ needs.vars.outputs.pr }}
  #         tags: prod
